
description: "I am a goal-driven and technically proficient individual with a strong passion for continuous learning. I prioritize respect and professionalism in all my interactions. Ultimately, I strive to be a fair and innovative leader, committed to using my skills to drive meaningful impact and contribute to the growth and success of any organization I am part of."
baseurl: ""
url: "https://georgemugale.github.io"
theme: minima
theme: jekyll-theme-minimal

github_username: georgemugale
email: georgeapril202020@gmail.com
linkedin_username: george-mugale-2175892b2
